name: Notify Slack on PR opened

on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: read

jobs:
  notify-slack:
    name: Notify Slack
    uses: PayMee-Brasil/platform-gh-workflows/.github/workflows/slack-pr-opened-notification.yml@main
    with:
      repo_name: ${{ github.repository }}
      pr_number: ${{ github.event.pull_request.number }}
      pr_title: ${{ github.event.pull_request.title }}
      pr_author: ${{ github.event.pull_request.user.login }}
      pr_url: ${{ github.event.pull_request.html_url }}
      source_branch: ${{ github.event.pull_request.head.ref }}
      target_branch: ${{ github.event.pull_request.base.ref }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
